name: tensorflow_envs3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - abseil-cpp=20200923.3
  - absl-py=0.13.0
  - aiohttp=3.7.4
  - alsa-lib=1.2.3
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - atk-1.0=2.36.0
  - attrs=21.2.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cached-property=1.5.2
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=3.0.4
  - click=8.0.1
  - coverage=5.5
  - cryptography=3.4.7
  - cython=0.29.24
  - dbus=1.13.6
  - expat=2.4.1
  - ffmpeg=4.3.2
  - flatbuffers=2.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gast=0.4.0
  - gdk-pixbuf=2.42.6
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - graphviz=2.48.0
  - grpcio=1.36.1
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - gtk2=2.24.33
  - gts=0.7.6
  - h5py=3.2.1
  - harfbuzz=2.8.2
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - imageio=2.9.0
  - importlib-metadata=3.10.0
  - intel-openmp=2021.3.0
  - jasper=1.900.1
  - joblib=1.0.1
  - jpeg=9d
  - keras=2.4.3
  - keras-base=2.4.3
  - keras-preprocessing=1.1.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.78.0
  - libedit=3.1.20210216
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=11.1.0
  - libgd=2.3.2
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.3
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.41.0
  - libogg=1.3.4
  - libopencv=4.5.1
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.14.0
  - librsvg=2.50.7
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - multidict=5.1.0
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - ncurses=6.2
  - nettle=3.6
  - nspr=4.30
  - nss=3.67
  - numpy=1.20.3
  - numpy-base=1.20.3
  - oauthlib=3.1.1
  - olefile=0.46
  - opencv=4.5.1
  - openh264=2.1.1
  - openssl=1.1.1k
  - opt_einsum=3.3.0
  - pango=1.48.9
  - pcre=8.45
  - pillow=8.3.1
  - pip=21.2.4
  - pixman=0.40.0
  - protobuf=3.14.0
  - pthread-stubs=0.4
  - py-opencv=4.5.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pydot=1.2.4
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.8
  - python-flatbuffers=1.12
  - python-graphviz=0.17
  - python_abi=3.8
  - pyyaml=5.4.1
  - qt=5.12.9
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - setuptools=52.0.0
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.36.0
  - tensorboard=2.5.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.5.0
  - tensorflow-base=2.5.0
  - tensorflow-estimator=2.5.0
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - urllib3=1.26.6
  - werkzeug=1.0.1
  - wheel=0.35.1
  - wrapt=1.12.1
  - x264=1!161.3030
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - tqdm
  - pip:
    - patchify==0.2.3
