name: tensorflow_envs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - absl-py=0.13.0
  - astor=0.8.1
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.7.5
  - cached-property=1.5.2
  - cairo=1.14.12
  - certifi=2021.5.30
  - coverage=5.5
  - cython=0.29.24
  - expat=2.4.1
  - ffmpeg=4.0
  - fontconfig=2.13.1
  - freeglut=3.0.0
  - freetype=2.10.4
  - fribidi=1.0.10
  - gast=0.2.2
  - glib=2.63.1
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - graphviz=2.40.1
  - grpcio=1.36.1
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - imageio=2.9.0
  - importlib-metadata=3.10.0
  - intel-openmp=2021.3.0
  - jasper=2.0.14
  - jbig=2.1
  - joblib=1.0.1
  - jpeg=9d
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-base=2.3.1
  - keras-preprocessing=1.1.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libdeflate=1.7
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglu=9.0.0
  - libgomp=9.3.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markdown=3.3.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - opencv=3.4.2
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - opt_einsum=3.3.0
  - pango=1.42.4
  - pcre=8.45
  - pillow=8.3.1
  - pip=21.1.3
  - pixman=0.40.0
  - protobuf=3.14.0
  - py-opencv=3.4.2
  - pydot=1.3.0
  - pyparsing=2.4.7
  - python=3.7.7
  - python-graphviz=0.16
  - python_abi=3.7
  - pyyaml=5.4.1
  - readline=8.1
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tensorboard=1.15.0
  - tensorflow=1.15.0
  - tensorflow-base=1.15.0
  - tensorflow-estimator=1.15.1
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - typing_extensions=3.10.0.0
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - patchify==0.2.3
