name: tensorflow_envs2
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow=2.5.0
  - tensorboard=2.5.0
  - keras=2.4.3
  - imageio=2.9.0
  - scipy
  - libopencv
  - opencv
  - py-opencv
  - scikit-learn
  - pydot
  - python-graphviz
  - pip:
    - patchify==0.2.3
