name: tensorflow_envs
channels:
  - defaults
dependencies:
  - tensorflow=1.15
  - keras==2.3.1
  - imageio
  - scipy
  - opencv
  - scikit-learn
  - pydot
  - python-graphviz
  - pip:
    - patchify==0.2.3
